# Generated by Django 2.2 on 2020-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xyz', max_length=10)),
                ('hostel_type', models.CharField(max_length=7)),
            ],
        ),
    ]
