# Generated by Django 2.2 on 2020-04-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20200418_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='total_available_rooms',
            new_name='total_available_bedspace',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='total_booked_rooms',
            new_name='total_bedspace',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='total_rooms',
            new_name='total_booked_bedspace',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='hostel_type',
        ),
    ]
