search_choices= {
     'IBH': 'PETER JASPER AKINOLA HOSTEL',
    'JAH': 'JOSEPH ADETILOYE HOSTEL',
    'DLW': 'DIOSES OF LAGOST WEST FEMALE HOSTEL',
    'UFH': 'UNIVERSITY FEMALE HOSTEL',
}



