# Generated by Django 2.2 on 2020-04-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=5)),
                ('hall_name', models.CharField(default='PJAH', max_length=10)),
                ('date_of_booking', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name=' Booking')),
                ('is_departed', models.BooleanField(default=False, verbose_name='Departed')),
                ('room_preference', models.CharField(choices=[('BEDSPACE1', 'BEDSPACE1'), ('BEDSPACE2', 'BEDSPACE2'), ('BEDSPACE3', 'BEDSPACE3'), ('BEDSPACE4', 'BEDSPACE4')], default='BEDSPACE1', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_allotted', models.CharField(choices=[('1', 'PJAH'), ('2', 'JAH'), ('3', 'DLW'), ('4', 'UFH')], default='1', max_length=10)),
                ('room_no', models.CharField(default='0000', max_length=10)),
                ('room_type', models.CharField(choices=[('BEDSPACE1', 'BEDSPACE1'), ('BEDSPACE2', 'BEDSPACE2'), ('BEDSPACE3', 'BEDSPACE3'), ('BEDSPACE4', 'BEDSPACE4')], default='BEDSPACE1', max_length=10)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor')),
            ],
        ),
    ]
