# Generated by Django 2.2 on 2020-04-17 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='hall_name',
        ),
        migrations.AddField(
            model_name='visitor',
            name='from_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
        migrations.AddField(
            model_name='visitor',
            name='hostel_name',
            field=models.CharField(default='PJAH', max_length=5),
        ),
        migrations.AddField(
            model_name='visitor',
            name='no_of_rooms_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visitor',
            name='to_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
    ]
