# Generated by Django 2.2 on 2020-04-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20200417_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='no_of_rooms_required',
        ),
    ]
