# Generated by Django 2.2 on 2020-04-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_remove_visitor_no_of_rooms_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='no_of_rooms_required',
            field=models.IntegerField(default=1),
        ),
    ]
