# Generated by Django 2.2 on 2020-04-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_auto_20200417_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='hostel_name',
            field=models.CharField(choices=[('PJAH', 'PJAH'), ('JAH', 'JAH'), ('DLW', 'DLW'), ('UFH', 'UFH')], default='PJAH', max_length=5),
        ),
    ]
