# Generated by Django 2.2 on 2020-04-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_bookinginfo_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='hostel_allotted',
            field=models.CharField(choices=[('1', 'PETER JASPER AKINOLA'), ('2', 'JOSEPH ADETILOYE HOSTEL'), ('3', 'DIOSES OF LAGOS WEST FEMALE HOSTEL'), ('4', 'UNIVERSITY FEMALE HOSTEL')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='hostel_name',
            field=models.CharField(choices=[('IB', 'PETER JASPER AKINOLA HOSTEL'), ('JAH', 'JOSEPH ADETILOYE HOSTEL'), ('DLW', 'DIOSES OF LAGOST WEST FEMALE HOSTEL'), ('UFH', 'UNIVERSITY FEMALE HOSTEL')], default='PJAH', max_length=5),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='hostel_name',
            field=models.CharField(choices=[('IB', 'PETER JASPER AKINOLA HOSTEL'), ('JAH', 'JOSEPH ADETILOYE HOSTEL'), ('DLW', 'DIOSES OF LAGOST WEST FEMALE HOSTEL'), ('UFH', 'UNIVERSITY FEMALE HOSTEL')], default='PJAH', max_length=5),
        ),
    ]
