# Generated by Django 2.2 on 2020-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_auto_20200417_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginfo',
            old_name='room_no',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='bookinginfo',
            old_name='room_type',
            new_name='room_preference',
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='hostel_name',
            field=models.CharField(choices=[('IBH', 'PETER JASPER AKINOLA HOSTEL'), ('JAH', 'JOSEPH ADETILOYE HOSTEL'), ('DLW', 'DIOSES OF LAGOST WEST FEMALE HOSTEL'), ('UFH', 'UNIVERSITY FEMALE HOSTEL')], default='IBH', max_length=5),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='hostel_name',
            field=models.CharField(choices=[('IBH', 'PETER JASPER AKINOLA HOSTEL'), ('JAH', 'JOSEPH ADETILOYE HOSTEL'), ('DLW', 'DIOSES OF LAGOST WEST FEMALE HOSTEL'), ('UFH', 'UNIVERSITY FEMALE HOSTEL')], default='IBH', max_length=5),
        ),
    ]
